### ISSUE TITLE
Can't connect to SugarCRM

### ISSUE THREAD

**Issue by JAW-Dev** [curtismchale/Gravity-Forms-and-SugarCRM#1]
I'm setting up my client's gravityforms to add leads to their sugarCRM account. I'm not really sure if it's even connecting. 

I have this for the newsoap_client param 

```
https://the_client.sugarondemand.com/
```

and a function for each form that looks like this

```
function gf_9( $entry ){

  $sugar = new SugarCRMWebServices( 'username', 'password' );

  // Login  and create a new lead
  $sugar->login();
  $result = $sugar->createLead(array(
    'lead_source'             => 'Form Name',
    'lead_source_description' => 'Description',
    'lead_status'             => 'New',
    'name'                    => $entry[1],
    'email'                   => $entry[2],
    'organization'            => $entry[3]
  ));

}
add_action( 'gform_after_submission_9', 'gf_9', 10, 2 );
```

Everything looks like it does in your tutorial, but it's not sending anything to the sugarCRM account. Is there something I'm missing?

**Comment by curtismchale** [comment]
No idea. Not really working on this anymore so it's unlikely I'll look in to it.

I'll take a pull request if there is a fix in my basic work though.
