### ISSUE TITLE
gform_after_submission not being called

### ISSUE THREAD

**Issue by mageguild** [curtismchale/Gravity-Forms-and-SugarCRM#2]
I have installed this onto our website but it does not seem to be loading for me.  
When I run this code locally without the Gravity form dependency locally, it works fine.  It seems that the gform_after_submission is not triggering.  

Any suggestions?

**Comment by curtismchale** [comment]
Gravity Forms probably changed their hooks which would mean this needs to be updated. I'm not really maintaining it anymore or working with Sugar so read through the GF docs and find the hook you need.
